import type { GalleryItem } from '../types';

export const galleryItems: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Crispy Ghee Roast Dosa',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80',
    description: 'Golden, paper-crisp dosa served with fresh coconut and coriander chutneys and piping hot sambar.',
    aspectRatio: 'wide',
  },
  {
    id: 'gal-2',
    title: 'Traditional Warm Ambience',
    category: 'interior',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    description: 'Our serene dining hall blending South Indian brass aesthetics with comfortable contemporary seating.',
    aspectRatio: 'wide',
  },
  {
    id: 'gal-3',
    title: 'Royal South Indian Thali',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=80',
    description: 'A grand festive spread served on a fresh banana leaf with over 12 traditional accompaniments.',
    aspectRatio: 'square',
  },
  {
    id: 'gal-4',
    title: 'Freshly Steamed Mini Idlis',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80',
    description: 'Fluffy button idlis soaked in freshly made spiced drumstick sambar.',
    aspectRatio: 'square',
  },
  {
    id: 'gal-5',
    title: 'Artisan Chettinad Spice Blending',
    category: 'kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
    description: 'Our master chefs hand-roasting whole coriander, star anise, and Tellicherry pepper every morning.',
    aspectRatio: 'tall',
  },
  {
    id: 'gal-6',
    title: 'Family Gatherings & Celebrations',
    category: 'events',
    imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1200&q=80',
    description: 'Spacious banquet and courtyard spaces perfect for milestone birthdays, anniversaries, and get-togethers.',
    aspectRatio: 'wide',
  },
  {
    id: 'gal-7',
    title: 'Kumbakonam Degree Filter Coffee',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80',
    description: 'Freshly decocted chicory-laced coffee frothed to perfection in traditional brass davarah-tumbler.',
    aspectRatio: 'square',
  },
  {
    id: 'gal-8',
    title: 'Live Dosa Station & Tandoor Flame',
    category: 'kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1200&q=80',
    description: 'Precision timing on cast iron griddles seasoned over decades for that iconic crisp texture.',
    aspectRatio: 'tall',
  },
  {
    id: 'gal-9',
    title: 'Intimate Courtyard Seating',
    category: 'interior',
    imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80',
    description: 'Warm lighting, indoor greenery, and private booths designed for relaxed family lunches.',
    aspectRatio: 'wide',
  },
  {
    id: 'gal-10',
    title: 'Clay Pot Chettinad Dum Biryani',
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80',
    description: 'Sealed with dough and slow cooked over gentle embers to seal in the aromas.',
    aspectRatio: 'square',
  },
  {
    id: 'gal-11',
    title: 'Private Dining & Corporate Dinners',
    category: 'events',
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80',
    description: 'Curated multi-course tasting menus for corporate teams and special family milestones.',
    aspectRatio: 'wide',
  },
  {
    id: 'gal-12',
    title: 'Hygienic & Modern Preparation Kitchen',
    category: 'kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
    description: 'Spotless stainless-steel prep stations adhering to the highest standards of culinary safety.',
    aspectRatio: 'wide',
  },
];
