import type { MenuItem, MenuCategory } from '../types';

export const menuCategories: MenuCategory[] = [
  { id: 'all', name: 'Full Menu', tagline: 'Explore our complete culinary offerings' },
  { id: 'breakfast', name: 'Breakfast', tagline: 'Crispy dosas, fluffy idlis & steaming hot morning specials' },
  { id: 'south-indian', name: 'South Indian Classics', tagline: 'Heirloom tiffin dishes and homestyle favourites' },
  { id: 'biryani', name: 'Aromatic Biryanis', tagline: 'Slow-cooked fragrant basmati rice infused with whole spices' },
  { id: 'vegetarian', name: 'Vegetarian Specialties', tagline: 'Rich gravies, paneer delights & spiced stir-fries' },
  { id: 'non-vegetarian', name: 'Non-Vegetarian Curries', tagline: 'Signature Chettinad gravies, coastal fish & roasted meats' },
  { id: 'desserts', name: 'Traditional Desserts', tagline: 'Sweet finishes crafted with jaggery, milk & dry fruits' },
  { id: 'beverages', name: 'Beverages & Coffee', tagline: 'Authentic Kumbakonam brass filter coffee and coolers' },
];

export const menuItems: MenuItem[] = [
  // --- SIGNATURE & BREAKFAST ---
  {
    id: 'ghee-roast-dosa',
    name: 'Ghee Roast Dosa',
    description: 'Crispy golden dosa finished with aromatic ghee and served with sambar and house chutneys.',
    price: 180,
    category: 'breakfast',
    isVegetarian: true,
    isBestseller: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served with 3 chutneys & drumstick sambar',
    allergens: ['Dairy'],
  },
  {
    id: 'mini-idli-sambar',
    name: 'Mini Idli Sambar',
    description: 'Soft bite-sized idlis soaked in flavourful sambar and topped with fresh coriander.',
    price: 140,
    category: 'south-indian',
    isVegetarian: true,
    isBestseller: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    servingInfo: '14 mini idlis immersed in hot spiced sambar with ghee drizzle',
  },
  {
    id: 'steamed-idli-vada',
    name: 'Idli (2 Pcs)',
    description: 'Pillowy soft fermented rice and lentil cakes steamed to perfection, accompanied by coconut chutney.',
    price: 80,
    category: 'breakfast',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served with 2 house chutneys and sambar',
  },
  {
    id: 'medu-vada',
    name: 'Medu Vada (2 Pcs)',
    description: 'Crispy on the outside, fluffy inside lentil doughnuts tempered with peppercorns, curry leaves and ginger.',
    price: 90,
    category: 'breakfast',
    isVegetarian: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Golden brown fritters with coconut & tomato chutney',
  },
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    description: 'Crisp fermented crepe filled with spiced potato and onion mash, accompanied by trio of chutneys.',
    price: 150,
    category: 'breakfast',
    isVegetarian: true,
    isBestseller: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served hot from the griddle with sambar',
  },
  {
    id: 'ven-pongal',
    name: 'Ven Pongal',
    description: 'Comforting creamy rice and yellow moong dal cooked with crushed black pepper, cumin, ginger and roasted cashews.',
    price: 120,
    category: 'breakfast',
    isVegetarian: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Topped with pure desi ghee and cashew nuts',
    allergens: ['Nuts', 'Dairy'],
  },

  // --- SOUTH INDIAN CLASSICS ---
  {
    id: 'plain-dosa',
    name: 'Plain Dosa',
    description: 'Traditional thin and crispy paper-style crepe made from fermented rice and black gram batter.',
    price: 120,
    category: 'south-indian',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served with signature white and red chutneys',
  },
  {
    id: 'mysore-masala-dosa',
    name: 'Mysore Masala Dosa',
    description: 'Crisp dosa smeared with spicy roasted red garlic chutney and stuffed with seasoned potato filling.',
    price: 180,
    category: 'south-indian',
    isVegetarian: true,
    isChefSpecial: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Rich and spicy, served with fresh coconut chutney',
  },
  {
    id: 'onion-uttapam',
    name: 'Onion Uttapam',
    description: 'Thick, fluffy savory pancake topped with finely diced shallots, green chillies and fresh coriander leaves.',
    price: 160,
    category: 'south-indian',
    isVegetarian: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Pan-roasted on slow flame with sesame oil',
  },
  {
    id: 'poori-masala',
    name: 'Poori Masala (3 Pcs)',
    description: 'Puffy whole-wheat deep-fried bread served with a mildly spiced homestyle potato and onion curry.',
    price: 140,
    category: 'south-indian',
    isVegetarian: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served piping hot with coconut chutney',
  },

  // --- BIRYANI ---
  {
    id: 'chettinad-chicken-biryani',
    name: 'Chicken Biryani',
    description: 'Fragrant Seeraga Samba rice cooked with succulent chicken cuts, mint, roasted shallots and artisanal Chettinad spices.',
    price: 280,
    category: 'biryani',
    isVegetarian: false,
    isBestseller: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served with onion raita, brinjal gravy (dalcha) and boiled egg',
  },
  {
    id: 'mutton-biryani',
    name: 'Mutton Biryani',
    description: 'Tender baby mutton pieces slow-cooked in dum style with aromatic spices and caramelized onion rice.',
    price: 360,
    category: 'biryani',
    isVegetarian: false,
    isChefSpecial: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served with signature salna and cucumber curd raita',
  },
  {
    id: 'vegetable-biryani',
    name: 'Vegetable Biryani',
    description: 'Fragrant basmati rice layered with seasonal vegetables and freshly ground spices.',
    price: 240,
    category: 'biryani',
    isVegetarian: true,
    isBestseller: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Cooked in sealed earthenware pot with cooling raita',
  },
  {
    id: 'paneer-biryani',
    name: 'Paneer Biryani',
    description: 'Marinated cottage cheese cubes layered with spiced saffron basmati rice, browned onions and fresh herbs.',
    price: 260,
    category: 'biryani',
    isVegetarian: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served with mixed vegetable raita and gravy',
  },

  // --- VEGETARIAN SPECIALTIES ---
  {
    id: 'paneer-pepper-fry',
    name: 'Paneer Pepper Fry',
    description: 'Cubes of soft paneer tossed with cracked pepper, onions, curry leaves and South Indian spices.',
    price: 260,
    category: 'vegetarian',
    isVegetarian: true,
    isBestseller: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Dry starter tossed on high flame',
    allergens: ['Dairy'],
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    description: 'Tender cottage cheese cubes simmered in a rich, buttery tomato and cashew silk gravy with fenugreek.',
    price: 250,
    category: 'vegetarian',
    isVegetarian: true,
    spiceLevel: 1,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Best paired with Butter Naan or Roti',
    allergens: ['Dairy', 'Nuts'],
  },
  {
    id: 'mushroom-pepper-fry',
    name: 'Mushroom Pepper Fry',
    description: 'Fresh button mushrooms sautéed with crushed Tellicherry black pepper, shallots and aromatic curry leaves.',
    price: 220,
    category: 'vegetarian',
    isVegetarian: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Signature Chettinad style dry appetizer',
  },
  {
    id: 'veg-chettinad',
    name: 'Veg Chettinad Curry',
    description: 'Assorted farm vegetables simmered in an intensely aromatic roasted coconut, star anise and stone-ground spice gravy.',
    price: 230,
    category: 'vegetarian',
    isVegetarian: true,
    isChefSpecial: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Authentic Karaikudi recipe',
  },

  // --- NON-VEGETARIAN CURRIES ---
  {
    id: 'chettinad-chicken',
    name: 'Chettinad Chicken',
    description: 'Tender chicken cooked with roasted spices, curry leaves, coconut and traditional Chettinad flavours.',
    price: 320,
    category: 'non-vegetarian',
    isVegetarian: false,
    isBestseller: true,
    spiceLevel: 3,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Signature dish cooked with 18 roasted spices',
  },
  {
    id: 'chicken-65',
    name: 'Chicken 65',
    description: 'Crispy fried chicken florets marinated in spiced yoghurt, curry leaves, ginger and red chilli blend.',
    price: 240,
    category: 'non-vegetarian',
    isVegetarian: false,
    isBestseller: true,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Tossed with fried curry leaves and lemon wedges',
  },
  {
    id: 'mutton-pepper-fry',
    name: 'Mutton Pepper Fry',
    description: 'Tender chunks of slow-cooked goat meat tossed with caramelized onions, roasted garlic and freshly crushed black pepper.',
    price: 380,
    category: 'non-vegetarian',
    isVegetarian: false,
    isChefSpecial: true,
    spiceLevel: 3,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Rich, peppery dry roast prepared in iron kadai',
  },
  {
    id: 'meen-kuzhambu',
    name: 'Traditional Fish Curry',
    description: 'Fresh local catch simmered in a tangy tamarind, shallot and fenugreek gravy finished with coconut milk.',
    price: 300,
    category: 'non-vegetarian',
    isVegetarian: false,
    spiceLevel: 2,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Earthen pot specialty served with steamed rice',
  },

  // --- DESSERTS ---
  {
    id: 'elaneer-payasam',
    name: 'Elaneer Payasam',
    description: 'Signature South Indian dessert crafted with tender coconut pulp, rich reduced milk, cardamom and toasted cashews.',
    price: 140,
    category: 'desserts',
    isVegetarian: true,
    isChefSpecial: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served chilled in clay bowl',
    allergens: ['Dairy', 'Nuts'],
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun (2 Pcs)',
    description: 'Soft golden milk dumplings soaked in saffron and rose water infused sugar syrup with pistachio garnish.',
    price: 100,
    category: 'desserts',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1593798605675-5f25a7493fa5?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served warm with a hint of green cardamom',
    allergens: ['Dairy', 'Nuts', 'Gluten'],
  },
  {
    id: 'house-ice-cream',
    name: 'Artisan Ice Cream',
    description: 'Rich artisanal ice cream available in Tender Coconut, Saffron Kulfi, or Alphonso Mango flavours.',
    price: 90,
    category: 'desserts',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Two generous scoops topped with roasted almonds',
    allergens: ['Dairy'],
  },

  // --- BEVERAGES ---
  {
    id: 'filter-coffee',
    name: 'Filter Coffee',
    description: 'Traditional South Indian filter coffee brewed fresh with chicory blend, frothy milk and served hot in brass dabarah.',
    price: 90,
    category: 'beverages',
    isVegetarian: true,
    isBestseller: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Authentic Kumbakonam degree coffee style',
    allergens: ['Dairy'],
  },
  {
    id: 'masala-tea',
    name: 'Masala Chai',
    description: 'Full-bodied black tea brewed with fresh ginger, cardamom pods, cinnamon and whole milk.',
    price: 70,
    category: 'beverages',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Steaming hot spiced tea',
    allergens: ['Dairy'],
  },
  {
    id: 'fresh-lime-soda',
    name: 'Fresh Lime Soda',
    description: 'Refreshing fizzy soda infused with freshly squeezed lime juice, mint sprigs and your choice of sweet or salted.',
    price: 100,
    category: 'beverages',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Served chilled over crushed ice',
  },
  {
    id: 'badam-milk',
    name: 'Badam Milk',
    description: 'Traditional nourishing warm almond milk flavored with genuine Kashmiri saffron strands and crushed green cardamom.',
    price: 120,
    category: 'beverages',
    isVegetarian: true,
    spiceLevel: 0,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    servingInfo: 'Topped with slivered pistachios and almonds',
    allergens: ['Dairy', 'Nuts'],
  },
];
